<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel();
?>
<form class="form contact" action="<?= $block->escapeUrl($block->getFormAction()) ?>" id="contact-form" method="post" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
        <div class="field note no-label">
            <?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?>
        </div>
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($viewModel->getUserName()) ?>" class="input-text letters-only" type="text" data-validate="{required:true, minlength:3}" />
            </div>
        </div>
        <div class="field name">
            <label class="label" for="lastname"><span><?= $block->escapeHtml(__('Last name')) ?></span></label>
            <div class="control">
                <input name="lastname" id="lastname" title="<?= $block->escapeHtmlAttr(__('Last name')) ?>" value="" class="input-text letters-only" type="text" data-validate="{required:false, minlength:3}" />
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field date">
            <label class="label" for="date"><span><?= $block->escapeHtml(__('Date')) ?></span></label>
            <div class="control">
                <input name="date" id="date" title="<?= $block->escapeHtmlAttr(__('Date')) ?>" value="" class="input-text" type="text" />
            </div>
        </div>
        <div class="field telephone required">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>" class="input-text" type="tel" data-validate="{required:true}" />
            </div>
        </div>
        <div class="field topic">
            <label class="label" for="topic"><span><?= $block->escapeHtml(__('Topic')) ?></span></label>
            <div class="control">
                <select name="topic" id="topic" class="input-text">
                    <option value="" selected disabled>Select the message topic</option>
                    <option value="<?= $block->escapeHtmlAttr(__('Invoice')) ?>">Invoice</option>
                    <option value="<?= $block->escapeHtmlAttr(__('B2B')) ?>">B2B</option>
                    <option value="<?= $block->escapeHtmlAttr(__('B2C')) ?>">B2C</option>
                </select>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment">
                <span><?= $block->escapeHtml(__('Description')) ?></span>
            </label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Description')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true, minlength:20, maxlength:200}"><?= $block->escapeHtml($viewModel->getUserComment()) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>

<script type="text/javascript">
    require([
        'jquery',
        'mage/mage',
        'maskedinput'
    ], function($) {
        $("#date").mask("99/99/9999");
        $("#telephone").mask("(999) 999-9999");
    });
</script>